version: '3'

# Include sub-taskfiles
includes:
  setup:
    taskfile: .taskfile/setup.yml
  services:
    taskfile: .taskfile/services.yml
  backup:
    taskfile: .taskfile/backup.yml
  maintenance:
    taskfile: .taskfile/maintenance.yml
  utilities:
    taskfile: .taskfile/utilities.yml

vars:
  BACKUP_DIR: ./backups
  TIMESTAMP: '{{now | date "2006-01-02_15-04-05"}}'
  COMPOSE_FILE: docker-compose.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
