name: Security Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  # Container security scan removed - no Docker images built

  filesystem-security-scan:
    name: Filesystem Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'

      - name: Upload Trivy filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'

  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: 
          head: main
          extra_args: --debug --only-verified

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  supply-chain-security:
    name: Supply Chain Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: ossf-scorecard-results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OSSF Scorecard results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ossf-scorecard-results.sarif

  dependency-security-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        if: hashFiles('package.json') != ''

      - name: Install Node.js dependencies
        run: npm ci
        if: hashFiles('package.json') != ''

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
        if: hashFiles('package.json') != ''

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python security tools
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit semgrep

      - name: Run Safety check for Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            safety check --file requirements.txt --json --output safety-report.json || true
          fi
        continue-on-error: true

      - name: Run Bandit security linter
        run: |
          if [ -d "." ]; then
            bandit -r . -f json -o bandit-report.json || true
          fi
        continue-on-error: true

      - name: Run Semgrep SAST
        run: |
          semgrep --config=auto --json --output=semgrep-results.json . || true
        continue-on-error: true

      - name: Upload security scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
            semgrep-results.json
        if: always()

  # Docker security best practices removed - no Dockerfile present

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [
      codeql-analysis,
      filesystem-security-scan,
      secrets-detection,
      supply-chain-security,
      dependency-security-scan
    ]
    if: always()
    steps:
      - name: Security Analysis Summary
        run: |
          echo "## 🔐 Security Analysis Summary"
          echo ""
          echo "| Check | Status |"
          echo "|-------|--------|"
          echo "| CodeQL Analysis | ${{ needs.codeql-analysis.result }} |"
          echo "| Filesystem Security Scan | ${{ needs.filesystem-security-scan.result }} |"
          echo "| Secrets Detection | ${{ needs.secrets-detection.result }} |"
          echo "| Supply Chain Security | ${{ needs.supply-chain-security.result }} |"
          echo "| Dependency Security Scan | ${{ needs.dependency-security-scan.result }} |"
          echo ""
          echo "Docker-related scans skipped (no container images built)"
          echo ""

          # Check if any critical security checks failed
          if [[ "${{ needs.secrets-detection.result }}" == "failure" ]]; then
            echo "🚨 **CRITICAL**: Secrets detected in repository!"
            exit 1
          fi

          echo "✅ Security analysis completed. Check individual job results for details."
